---
driver:
  name: ec2
  aws_ssh_key_id: MyKeyPair
  region: us-west-2
  availability_zone: a
  instance_type: t2.micro
  image_id: ami-0a00ce72
  security_group_ids: ['sg-309dd94d']
  retryable_tries: 120

provisioner:
  name: chef_zero

verifier:
  name: inspec

transport:
  ssh_key: ~/.ssh/MyKeyPair.pem

platforms:
  - name: ubuntu

suites:
  - name: setup
    run_list:
      - recipe[middleman_install::default]
    verifier:
      inspec_tests:
         - test/smoke/default
    attributes:
